apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-proxy-manager

labels:
  - pairs:
      app.kubernetes.io/name: nginx-proxy-manager
      app.kubernetes.io/part-of: nginx-proxy-manager

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: jc21/nginx-proxy-manager
    newTag: "2.15.1"
